# c:\Users\Usuario\Desktop\Proyectos\Web personal\Diseño 3\_config.yml
title: Santiago González Pérez
description: "Página web personal de Santiago González Pérez. Un registro de lecturas, artículos académicos y más."
url: "https://santiagogonzalezperez.github.io/"

excerpt_separator: "<!--more-->"

# Plugins
plugins:
  - jekyll-feed

# Personalización del tema Minima
minima:
  skin: classic
  social_links:
